### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by apsun** [Zonglin-Li6565/SmartAC#1]
I tried running `javac main.cpp` but it keeps giving me some random errors (should be fine since they scrolled off the screen though). But when I try to run the program it tells me I don't have an operating system installed.

I made some changes to the makefile and it successfully compiled, but when I ran `./server.js` it just causes my iPad to reboot. Since I got an A in CS225, I thought it might be caused by undefined behavior so I tried running `valgrind LICENSE`, but then my refrigerator exploded and my cat died.

Please help, I'm starting to panic here...

**Comment by zli117** [comment]
Apparently, there are some the problems with your kernel. This might help:
Take your laptop, hold it firmly with both your hands. Then, use as much force as possible, swing the laptop to your head. Repeat until it's fixed.

**Comment by apsun** [comment]
Instructions unclear, dick caught in ceiling fan

**Comment by zli117** [comment]
Have you ever tried?

**Comment by apsun** [comment]
I added a try-catch block to LICENSE but my cat is still dead. What do I do now?

**Comment by zli117** [comment]
So, now I believe the only available option is to climb up to your roof and jump off from it. This will definitely and permanently fix your problem.

**Comment by apsun** [comment]
Thanks, I tried that and now my cat is alive again!
